### ISSUE TITLE
Too slow initialization

### ISSUE THREAD

**Issue by nijel** [gammu/gammu#136]
When phone sends many unsolicited messages, the initialization takes too long:

```
Tue 2015/09/15 09:56:52: Sending simple AT command to wake up some devices
Tue 2015/09/15 09:56:52: SENDING frametype 0x00/length 0x03/3
Tue 2015/09/15 09:56:52: 41A|54T|0D                                                      AT.
Tue 2015/09/15 09:56:52: 1 "AT"
Tue 2015/09/15 09:56:52: 2 "OK"
Tue 2015/09/15 09:56:52: Checking line: OK
Tue 2015/09/15 09:56:52: AT reply state: 1
Tue 2015/09/15 09:56:52: RECEIVED frametype 0x00/length 0x09/9
Tue 2015/09/15 09:56:52: 41A|54T|0D |0D |0A |4FO|4BK|0D |0A                              AT...OK..
Tue 2015/09/15 09:56:53: 1 "^RSSI:23"
Tue 2015/09/15 09:56:53: Checking line: ^RSSI:23
Tue 2015/09/15 09:56:53: AT reply state: 4
Tue 2015/09/15 09:56:53: RECEIVED frametype 0x00/length 0x0A/10
Tue 2015/09/15 09:56:53: 5E^|52R|53S|53S|49I|3A:|322|333|0D |0A                          ^RSSI:23..
Tue 2015/09/15 09:56:53: 1 "^CSNR:-66,-3"
Tue 2015/09/15 09:56:53: Checking line: ^CSNR:-66,-3
Tue 2015/09/15 09:56:53: AT reply state: 4
Tue 2015/09/15 09:56:53: RECEIVED frametype 0x00/length 0x0E/14
Tue 2015/09/15 09:56:53: 5E^|43C|53S|4EN|52R|3A:|2D-|366|366|2C,|2D-|333|0D |0A          ^CSNR:-66,-3..
Tue 2015/09/15 09:56:56: 1 "^RSSI:23"
Tue 2015/09/15 09:56:56: Checking line: ^RSSI:23
Tue 2015/09/15 09:56:56: AT reply state: 4

... Continues for 5 minutes this way (receiving boot, rssi, at ok and boot signal) ...

Tue 2015/09/15 10:01:30: Enabling echo
Tue 2015/09/15 10:01:30: SENDING frametype 0x00/length 0x05/5
Tue 2015/09/15 10:01:30: 41A|54T|45E|311|0D                                              ATE1.
Tue 2015/09/15 10:01:30: 1 "ATE1"
Tue 2015/09/15 10:01:30: 2 "OK"
Tue 2015/09/15 10:01:30: Checking line: OK
Tue 2015/09/15 10:01:30: AT reply state: 1
Tue 2015/09/15 10:01:30: RECEIVED frametype 0x00/length 0x0B/11
```

This is spin off from #135

**Comment by nijel** [comment]
Gammu processes everything from the phone before it sends another command. And the phone seems to be sending these messages quite often. Can you please include a but more of the log to see how frequently do these arrive? It seems that sometimes Gammu is waiting too long.

**Comment by nijel** [comment]
Also can you please retry with changes done in ``delay-rewrite`` branch? I think it should make it better, though I don't have real device with me to test that it's correct...

**Comment by Bowser** [comment]
This is a complete log taken from now:
Tue 2015/09/15 10:52:19: [Gammu            - 1.36.6]
Tue 2015/09/15 10:52:19: [Connection       - "at"]
Tue 2015/09/15 10:52:19: [Connection index - 0]
Tue 2015/09/15 10:52:19: [Model type       - "at"]
Tue 2015/09/15 10:52:19: [Device           - "/dev/ttyUSB2"]
Tue 2015/09/15 10:52:19: [Running on       - Linux, kernel 3.16.0-4-amd64 (#1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04))]
Tue 2015/09/15 10:52:19: [Module           - "A2D|iPAQ|at|M20|S25|MC35|TC35|C35i|S65|S300|5110|5130|5190|5210|6110|6130|6150|6190|6210|6250|6310|6310i|6510|7110|8210|8250|8290|8310|8390|8850|8855|8890|8910|9110|9210"]
Tue 2015/09/15 10:52:19: Serial device: DTR is up, RTS is up, CAR is down, CTS is down
Tue 2015/09/15 10:52:19: Setting speed to 19200
Tue 2015/09/15 10:52:19: Escaping SMS mode
Tue 2015/09/15 10:52:19: SENDING frametype 0x00/length 0x02/2
Tue 2015/09/15 10:52:19: 1B |0D                                                          ..              
Tue 2015/09/15 10:53:01: Sending simple AT command to wake up some devices
Tue 2015/09/15 10:53:01: SENDING frametype 0x00/length 0x03/3
Tue 2015/09/15 10:53:01: 41A|54T|0D                                                      AT.             
Tue 2015/09/15 10:53:02: 1 "AT"
Tue 2015/09/15 10:53:02: 2 "OK"
Tue 2015/09/15 10:53:02: Checking line: OK
Tue 2015/09/15 10:53:02: AT reply state: 1
Tue 2015/09/15 10:53:02: RECEIVED frametype 0x00/length 0x09/9
Tue 2015/09/15 10:53:02: 41A|54T|0D |0D |0A |4FO|4BK|0D |0A                              AT...OK..       
Tue 2015/09/15 10:53:02: 1 "^BOOT:44964621,0,0,0,99"
Tue 2015/09/15 10:53:02: Checking line: ^BOOT:44964621,0,0,0,99
Tue 2015/09/15 10:53:02: AT reply state: 4
Tue 2015/09/15 10:53:02: RECEIVED frametype 0x00/length 0x19/25
Tue 2015/09/15 10:53:02: 5E^|42B|4FO|4FO|54T|3A:|344|344|399|366|344|366|322|311|2C,|300 ^BOOT:44964621,0
Tue 2015/09/15 10:53:02: 2C,|300|2C,|300|2C,|399|399|0D |0A                              ,0,0,99..       
Tue 2015/09/15 10:53:08: 1 "^RSSI:23"
Tue 2015/09/15 10:53:08: Checking line: ^RSSI:23
Tue 2015/09/15 10:53:08: AT reply state: 4
Tue 2015/09/15 10:53:08: RECEIVED frametype 0x00/length 0x0A/10
Tue 2015/09/15 10:53:08: 5E^|52R|53S|53S|49I|3A:|322|333|0D |0A                          ^RSSI:23..      
Tue 2015/09/15 10:53:08: 1 "^CSNR:-68,-6"
Tue 2015/09/15 10:53:08: Checking line: ^CSNR:-68,-6
Tue 2015/09/15 10:53:08: AT reply state: 4
Tue 2015/09/15 10:53:08: RECEIVED frametype 0x00/length 0x0E/14
Tue 2015/09/15 10:53:08: 5E^|43C|53S|4EN|52R|3A:|2D-|366|388|2C,|2D-|366|0D |0A          ^CSNR:-68,-6..  
Tue 2015/09/15 10:53:17: 1 "^RSSI:23"
Tue 2015/09/15 10:53:17: Checking line: ^RSSI:23
Tue 2015/09/15 10:53:17: AT reply state: 4
Tue 2015/09/15 10:53:17: RECEIVED frametype 0x00/length 0x0A/10
Tue 2015/09/15 10:53:17: 5E^|52R|53S|53S|49I|3A:|322|333|0D |0A                          ^RSSI:23..      
Tue 2015/09/15 10:53:17: 1 "^CSNR:-69,-4"
Tue 2015/09/15 10:53:17: Checking line: ^CSNR:-69,-4
Tue 2015/09/15 10:53:17: AT reply state: 4
Tue 2015/09/15 10:53:17: RECEIVED frametype 0x00/length 0x0E/14
Tue 2015/09/15 10:53:17: 5E^|43C|53S|4EN|52R|3A:|2D-|366|399|2C,|2D-|344|0D |0A          ^CSNR:-69,-4..  
Tue 2015/09/15 10:53:32: 1 "^BOOT:44964621,0,0,0,99"
Tue 2015/09/15 10:53:32: Checking line: ^BOOT:44964621,0,0,0,99
Tue 2015/09/15 10:53:32: AT reply state: 4
Tue 2015/09/15 10:53:32: RECEIVED frametype 0x00/length 0x19/25
Tue 2015/09/15 10:53:32: 5E^|42B|4FO|4FO|54T|3A:|344|344|399|366|344|366|322|311|2C,|300 ^BOOT:44964621,0
Tue 2015/09/15 10:53:32: 2C,|300|2C,|300|2C,|399|399|0D |0A                              ,0,0,99..       
Tue 2015/09/15 10:53:35: 1 "^RSSI:23"
Tue 2015/09/15 10:53:35: Checking line: ^RSSI:23
Tue 2015/09/15 10:53:35: AT reply state: 4
Tue 2015/09/15 10:53:35: RECEIVED frametype 0x00/length 0x0A/10
Tue 2015/09/15 10:53:35: 5E^|52R|53S|53S|49I|3A:|322|333|0D |0A                          ^RSSI:23..      
Tue 2015/09/15 10:53:35: 1 "^CSNR:-67,-3"
Tue 2015/09/15 10:53:35: Checking line: ^CSNR:-67,-3
Tue 2015/09/15 10:53:35: AT reply state: 4
Tue 2015/09/15 10:53:35: RECEIVED frametype 0x00/length 0x0E/14
Tue 2015/09/15 10:53:35: 5E^|43C|53S|4EN|52R|3A:|2D-|366|377|2C,|2D-|333|0D |0A          ^CSNR:-67,-3..  
Tue 2015/09/15 10:53:38: 1 "^RSSI:23"
Tue 2015/09/15 10:53:38: Checking line: ^RSSI:23
Tue 2015/09/15 10:53:38: AT reply state: 4
Tue 2015/09/15 10:53:38: RECEIVED frametype 0x00/length 0x0A/10
Tue 2015/09/15 10:53:38: 5E^|52R|53S|53S|49I|3A:|322|333|0D |0A                          ^RSSI:23..      
Tue 2015/09/15 10:53:38: 1 "^CSNR:-68,-4"
Tue 2015/09/15 10:53:38: Checking line: ^CSNR:-68,-4
Tue 2015/09/15 10:53:38: AT reply state: 4
Tue 2015/09/15 10:53:38: RECEIVED frametype 0x00/length 0x0E/14
Tue 2015/09/15 10:53:38: 5E^|43C|53S|4EN|52R|3A:|2D-|366|388|2C,|2D-|344|0D |0A          ^CSNR:-68,-4..  
Tue 2015/09/15 10:53:44: 1 "^RSSI:23"
Tue 2015/09/15 10:53:44: Checking line: ^RSSI:23
Tue 2015/09/15 10:53:44: AT reply state: 4
Tue 2015/09/15 10:53:44: RECEIVED frametype 0x00/length 0x0A/10
Tue 2015/09/15 10:53:44: 5E^|52R|53S|53S|49I|3A:|322|333|0D |0A                          ^RSSI:23..      
Tue 2015/09/15 10:53:44: 1 "^CSNR:-69,-6"
Tue 2015/09/15 10:53:44: Checking line: ^CSNR:-69,-6
Tue 2015/09/15 10:53:44: AT reply state: 4
Tue 2015/09/15 10:53:44: RECEIVED frametype 0x00/length 0x0E/14
Tue 2015/09/15 10:53:44: 5E^|43C|53S|4EN|52R|3A:|2D-|366|399|2C,|2D-|366|0D |0A          ^CSNR:-69,-6..  
Tue 2015/09/15 10:53:50: 1 "^RSSI:23"
Tue 2015/09/15 10:53:50: Checking line: ^RSSI:23
Tue 2015/09/15 10:53:50: AT reply state: 4
Tue 2015/09/15 10:53:50: RECEIVED frametype 0x00/length 0x0A/10
Tue 2015/09/15 10:53:50: 5E^|52R|53S|53S|49I|3A:|322|333|0D |0A                          ^RSSI:23..      
Tue 2015/09/15 10:53:50: 1 "^CSNR:-68,-4"
Tue 2015/09/15 10:53:50: Checking line: ^CSNR:-68,-4
Tue 2015/09/15 10:53:50: AT reply state: 4
Tue 2015/09/15 10:53:50: RECEIVED frametype 0x00/length 0x0E/14
Tue 2015/09/15 10:53:50: 5E^|43C|53S|4EN|52R|3A:|2D-|366|388|2C,|2D-|344|0D |0A          ^CSNR:-68,-4..  
Tue 2015/09/15 10:53:59: 1 "^RSSI:23"
Tue 2015/09/15 10:53:59: Checking line: ^RSSI:23
Tue 2015/09/15 10:53:59: AT reply state: 4
Tue 2015/09/15 10:53:59: RECEIVED frametype 0x00/length 0x0A/10
Tue 2015/09/15 10:53:59: 5E^|52R|53S|53S|49I|3A:|322|333|0D |0A                          ^RSSI:23..      
Tue 2015/09/15 10:53:59: 1 "^CSNR:-68,-5"
Tue 2015/09/15 10:53:59: Checking line: ^CSNR:-68,-5
Tue 2015/09/15 10:53:59: AT reply state: 4
Tue 2015/09/15 10:53:59: RECEIVED frametype 0x00/length 0x0E/14
Tue 2015/09/15 10:53:59: 5E^|43C|53S|4EN|52R|3A:|2D-|366|388|2C,|2D-|355|0D |0A          ^CSNR:-68,-5..  
Tue 2015/09/15 10:54:02: 1 "^BOOT:44964621,0,0,0,99"
Tue 2015/09/15 10:54:02: Checking line: ^BOOT:44964621,0,0,0,99
Tue 2015/09/15 10:54:02: AT reply state: 4
Tue 2015/09/15 10:54:02: RECEIVED frametype 0x00/length 0x19/25
Tue 2015/09/15 10:54:02: 5E^|42B|4FO|4FO|54T|3A:|344|344|399|366|344|366|322|311|2C,|300 ^BOOT:44964621,0
Tue 2015/09/15 10:54:02: 2C,|300|2C,|300|2C,|399|399|0D |0A                              ,0,0,99..       
Tue 2015/09/15 10:54:05: 1 "^RSSI:23"
Tue 2015/09/15 10:54:05: Checking line: ^RSSI:23
Tue 2015/09/15 10:54:05: AT reply state: 4
Tue 2015/09/15 10:54:05: RECEIVED frametype 0x00/length 0x0A/10
Tue 2015/09/15 10:54:05: 5E^|52R|53S|53S|49I|3A:|322|333|0D |0A                          ^RSSI:23..      
Tue 2015/09/15 10:54:05: 1 "^CSNR:-69,-7"
Tue 2015/09/15 10:54:05: Checking line: ^CSNR:-69,-7
Tue 2015/09/15 10:54:05: AT reply state: 4
Tue 2015/09/15 10:54:05: RECEIVED frametype 0x00/length 0x0E/14
Tue 2015/09/15 10:54:05: 5E^|43C|53S|4EN|52R|3A:|2D-|366|399|2C,|2D-|377|0D |0A          ^CSNR:-69,-7..  
Tue 2015/09/15 10:54:08: 1 "^RSSI:23"
Tue 2015/09/15 10:54:08: Checking line: ^RSSI:23
Tue 2015/09/15 10:54:08: AT reply state: 4
Tue 2015/09/15 10:54:08: RECEIVED frametype 0x00/length 0x0A/10
Tue 2015/09/15 10:54:08: 5E^|52R|53S|53S|49I|3A:|322|333|0D |0A                          ^RSSI:23..      
Tue 2015/09/15 10:54:08: 1 "^CSNR:-68,-5"
Tue 2015/09/15 10:54:08: Checking line: ^CSNR:-68,-5
Tue 2015/09/15 10:54:08: AT reply state: 4
Tue 2015/09/15 10:54:08: RECEIVED frametype 0x00/length 0x0E/14
Tue 2015/09/15 10:54:08: 5E^|43C|53S|4EN|52R|3A:|2D-|366|388|2C,|2D-|355|0D |0A          ^CSNR:-68,-5..  
Tue 2015/09/15 10:54:27: Enabling echo
Tue 2015/09/15 10:54:27: SENDING frametype 0x00/length 0x05/5
Tue 2015/09/15 10:54:27: 41A|54T|45E|311|0D                                              ATE1.           
Tue 2015/09/15 10:54:27: 1 "ATE1"
Tue 2015/09/15 10:54:27: 2 "OK"
Tue 2015/09/15 10:54:27: Checking line: OK
Tue 2015/09/15 10:54:27: AT reply state: 1
Tue 2015/09/15 10:54:27: RECEIVED frametype 0x00/length 0x0B/11
Tue 2015/09/15 10:54:27: 41A|54T|45E|311|0D |0D |0A |4FO|4BK|0D |0A                      ATE1...OK..     
Tue 2015/09/15 10:54:27: Trying Motorola mode switch
Tue 2015/09/15 10:54:27: SENDING frametype 0x00/length 0x0A/10
Tue 2015/09/15 10:54:27: 41A|54T|2B+|4DM|4FO|44D|45E|3D=|322|0D                          AT+MODE=2.      
Tue 2015/09/15 10:54:27: 1 "AT+MODE=2"
Tue 2015/09/15 10:54:27: 2 "ERROR"
Tue 2015/09/15 10:54:27: Checking line: ERROR
Tue 2015/09/15 10:54:27: AT reply state: 3
Tue 2015/09/15 10:54:27: RECEIVED frametype 0x00/length 0x13/19
Tue 2015/09/15 10:54:27: 41A|54T|2B+|4DM|4FO|44D|45E|3D=|322|0D |0D |0A |45E|52R|52R|4FO AT+MODE=2...ERRO
Tue 2015/09/15 10:54:27: 52R|0D |0A                                                      R..             
Tue 2015/09/15 10:54:27: Seems not to be supported
Tue 2015/09/15 10:54:27: Enabling CME errors
Tue 2015/09/15 10:54:27: SENDING frametype 0x00/length 0x0A/10
Tue 2015/09/15 10:54:27: 41A|54T|2B+|43C|4DM|45E|45E|3D=|311|0D                          AT+CMEE=1.      
Tue 2015/09/15 10:54:28: 1 "AT+CMEE=1"
Tue 2015/09/15 10:54:28: 2 "OK"
Tue 2015/09/15 10:54:28: Checking line: OK
Tue 2015/09/15 10:54:28: AT reply state: 1
Tue 2015/09/15 10:54:28: RECEIVED frametype 0x00/length 0x10/16
Tue 2015/09/15 10:54:28: 41A|54T|2B+|43C|4DM|45E|45E|3D=|311|0D |0D |0A |4FO|4BK|0D |0A  AT+CMEE=1...OK..
Tue 2015/09/15 10:54:28: SENDING frametype 0x00/length 0x09/9
Tue 2015/09/15 10:54:28: 41A|54T|2B+|43C|53S|43C|53S|3F?|0D                              AT+CSCS?.       
Tue 2015/09/15 10:54:28: 1 "AT+CSCS?"
Tue 2015/09/15 10:54:28: 2 "+CSCS: "GSM""
Tue 2015/09/15 10:54:28: 3 "OK"
Tue 2015/09/15 10:54:28: Checking line: OK
Tue 2015/09/15 10:54:28: AT reply state: 1
Tue 2015/09/15 10:54:28: RECEIVED frametype 0x00/length 0x1F/31
Tue 2015/09/15 10:54:28: 41A|54T|2B+|43C|53S|43C|53S|3F?|0D |0D |0A |2B+|43C|53S|43C|53S AT+CSCS?...+CSCS
Tue 2015/09/15 10:54:28: 3A:|20 |22"|47G|53S|4DM|22"|0D |0A |0D |0A |4FO|4BK|0D |0A      : "GSM"....OK.. 
Tue 2015/09/15 10:54:28: SENDING frametype 0x00/length 0x08/8
Tue 2015/09/15 10:54:28: 41A|54T|2B+|43C|47G|4DM|49I|0D                                  AT+CGMI.        
Tue 2015/09/15 10:54:29: 1 "AT+CGMI"
Tue 2015/09/15 10:54:29: 2 "huawei"
Tue 2015/09/15 10:54:29: 3 "OK"
Tue 2015/09/15 10:54:29: Checking line: OK
Tue 2015/09/15 10:54:29: AT reply state: 1
Tue 2015/09/15 10:54:29: RECEIVED frametype 0x00/length 0x18/24
Tue 2015/09/15 10:54:29: 41A|54T|2B+|43C|47G|4DM|49I|0D |0D |0A |68h|75u|61a|77w|65e|69i AT+CGMI...huawei
Tue 2015/09/15 10:54:29: 0D |0A |0D |0A |4FO|4BK|0D |0A                                  ....OK..        
Tue 2015/09/15 10:54:29: Manufacturer info received
Tue 2015/09/15 10:54:29: [Manufacturer: Huawei]
Tue 2015/09/15 10:54:29: SENDING frametype 0x00/length 0x0A/10
Tue 2015/09/15 10:54:29: 41A|54T|2B+|43C|53S|43C|53S|3D=|3F?|0D                          AT+CSCS=?.      
Tue 2015/09/15 10:54:29: 1 "AT+CSCS=?"
Tue 2015/09/15 10:54:29: 2 "+CSCS: ("IRA","GSM","UCS2")"
Tue 2015/09/15 10:54:29: 3 "OK"
Tue 2015/09/15 10:54:29: Checking line: OK
Tue 2015/09/15 10:54:29: AT reply state: 1
Tue 2015/09/15 10:54:29: RECEIVED frametype 0x00/length 0x2F/47
Tue 2015/09/15 10:54:29: 41A|54T|2B+|43C|53S|43C|53S|3D=|3F?|0D |0D |0A |2B+|43C|53S|43C AT+CSCS=?...+CSC
Tue 2015/09/15 10:54:29: 53S|3A:|20 |28(|22"|49I|52R|41A|22"|2C,|22"|47G|53S|4DM|22"|2C, S: ("IRA","GSM",
Tue 2015/09/15 10:54:29: 22"|55U|43C|53S|322|22"|29)|0D |0A |0D |0A |4FO|4BK|0D |0A      "UCS2")....OK.. 
Tue 2015/09/15 10:54:29: Chosen GSM as normal charset
Tue 2015/09/15 10:54:29: Chosen UCS2 as unicode charset
Tue 2015/09/15 10:54:29: Getting model
Tue 2015/09/15 10:54:29: SENDING frametype 0x00/length 0x08/8
Tue 2015/09/15 10:54:29: 41A|54T|2B+|43C|47G|4DM|4DM|0D                                  AT+CGMM.        
Tue 2015/09/15 10:54:29: 1 "AT+CGMM"
Tue 2015/09/15 10:54:29: 2 "E372"
Tue 2015/09/15 10:54:29: 3 "OK"
Tue 2015/09/15 10:54:29: Checking line: OK
Tue 2015/09/15 10:54:29: AT reply state: 1
Tue 2015/09/15 10:54:29: RECEIVED frametype 0x00/length 0x16/22
Tue 2015/09/15 10:54:29: 41A|54T|2B+|43C|47G|4DM|4DM|0D |0D |0A |45E|333|377|322|0D |0A  AT+CGMM...E372..
Tue 2015/09/15 10:54:29: 0D |0A |4FO|4BK|0D |0A                                          ..OK..          
Tue 2015/09/15 10:54:29: Unknown model, but it should still work
Tue 2015/09/15 10:54:29: [Model name: `E372']
Tue 2015/09/15 10:54:29: [Model data: `']
Tue 2015/09/15 10:54:29: [Model data: `unknown']
Tue 2015/09/15 10:54:29: [Connected model  - "E372"]
Tue 2015/09/15 10:54:29: Checking for OBEX support
Tue 2015/09/15 10:54:29: SENDING frametype 0x00/length 0x0B/11
Tue 2015/09/15 10:54:29: 41A|54T|2B+|43C|50P|52R|4FO|54T|3D=|3F?|0D                      AT+CPROT=?.     
Tue 2015/09/15 10:54:29: 1 "AT+CPROT=?"
Tue 2015/09/15 10:54:29: 2 "ERROR"
Tue 2015/09/15 10:54:29: Checking line: ERROR
Tue 2015/09/15 10:54:29: AT reply state: 3
Tue 2015/09/15 10:54:29: RECEIVED frametype 0x00/length 0x14/20
Tue 2015/09/15 10:54:29: 41A|54T|2B+|43C|50P|52R|4FO|54T|3D=|3F?|0D |0D |0A |45E|52R|52R AT+CPROT=?...ERR
Tue 2015/09/15 10:54:29: 4FO|52R|0D |0A                                                  OR..            
Tue 2015/09/15 10:54:29: Checking for SYNCML/OBEX support
Tue 2015/09/15 10:54:29: SENDING frametype 0x00/length 0x0C/12
Tue 2015/09/15 10:54:29: 41A|54T|2B+|53S|59Y|4EN|43C|4DM|4CL|3D=|3F?|0D                  AT+SYNCML=?.    
Tue 2015/09/15 10:54:29: 1 "AT+SYNCML=?"
Tue 2015/09/15 10:54:29: 2 "ERROR"
Tue 2015/09/15 10:54:29: Checking line: ERROR
Tue 2015/09/15 10:54:29: AT reply state: 3
Tue 2015/09/15 10:54:29: RECEIVED frametype 0x00/length 0x15/21
Tue 2015/09/15 10:54:29: 41A|54T|2B+|53S|59Y|4EN|43C|4DM|4CL|3D=|3F?|0D |0D |0A |45E|52R AT+SYNCML=?...ER
Tue 2015/09/15 10:54:29: 52R|4FO|52R|0D |0A                                              ROR..           
Tue 2015/09/15 10:54:29: Checking for SYNCML/OBEX support
Tue 2015/09/15 10:54:29: SENDING frametype 0x00/length 0x0D/13
Tue 2015/09/15 10:54:29: 41A|54T|24$|54T|53S|53S|50P|43C|53S|57W|3D=|3F?|0D              AT$TSSPCSW=?.   
Tue 2015/09/15 10:54:29: 1 "AT$TSSPCSW=?"
Tue 2015/09/15 10:54:29: 2 "ERROR"
Tue 2015/09/15 10:54:29: Checking line: ERROR
Tue 2015/09/15 10:54:29: AT reply state: 3
Tue 2015/09/15 10:54:29: RECEIVED frametype 0x00/length 0x16/22
Tue 2015/09/15 10:54:29: 41A|54T|24$|54T|53S|53S|50P|43C|53S|57W|3D=|3F?|0D |0D |0A |45E AT$TSSPCSW=?...E
Tue 2015/09/15 10:54:29: 52R|52R|4FO|52R|0D |0A                                          RROR..          
Tue 2015/09/15 10:54:29: Getting firmware versions
Tue 2015/09/15 10:54:29: SENDING frametype 0x00/length 0x08/8
Tue 2015/09/15 10:54:29: 41A|54T|2B+|43C|47G|4DM|52R|0D                                  AT+CGMR.        
Tue 2015/09/15 10:54:29: 1 "AT+CGMR"
Tue 2015/09/15 10:54:29: 2 "11.305.15.00.00"
Tue 2015/09/15 10:54:29: 3 "OK"
Tue 2015/09/15 10:54:29: Checking line: OK
Tue 2015/09/15 10:54:29: AT reply state: 1
Tue 2015/09/15 10:54:29: RECEIVED frametype 0x00/length 0x21/33
Tue 2015/09/15 10:54:29: 41A|54T|2B+|43C|47G|4DM|52R|0D |0D |0A |311|311|2E.|333|300|355 AT+CGMR...11.305
Tue 2015/09/15 10:54:29: 2E.|311|355|2E.|300|300|2E.|300|300|0D |0A |0D |0A |4FO|4BK|0D  .15.00.00....OK.
Tue 2015/09/15 10:54:29: 0A                                                              .               
Tue 2015/09/15 10:54:29: Received firmware version: "11.305.15.00.00"
Tue 2015/09/15 10:54:29: Number version is "11,305150"
Tue 2015/09/15 10:54:29: [Firmware version - "11.305.15.00.00"]
Tue 2015/09/15 10:54:29: [Connected]
Tue 2015/09/15 10:54:29: Entering GSM_SetIncomingCall
Tue 2015/09/15 10:54:29: Enabling incoming call notification
Tue 2015/09/15 10:54:29: SENDING frametype 0x00/length 0x0A/10
Tue 2015/09/15 10:54:29: 41A|54T|2B+|43C|4CL|49I|50P|3D=|311|0D                          AT+CLIP=1.      
Tue 2015/09/15 10:54:29: 1 "AT+CLIP=1"
Tue 2015/09/15 10:54:29: 2 "OK"
Tue 2015/09/15 10:54:29: Checking line: OK
Tue 2015/09/15 10:54:29: AT reply state: 1
Tue 2015/09/15 10:54:29: RECEIVED frametype 0x00/length 0x10/16
Tue 2015/09/15 10:54:29: 41A|54T|2B+|43C|4CL|49I|50P|3D=|311|0D |0D |0A |4FO|4BK|0D |0A  AT+CLIP=1...OK..
Tue 2015/09/15 10:54:29: SENDING frametype 0x00/length 0x09/9
Tue 2015/09/15 10:54:29: 41A|54T|2B+|43C|52R|43C|3D=|311|0D                              AT+CRC=1.       
Tue 2015/09/15 10:54:29: 1 "AT+CRC=1"
Tue 2015/09/15 10:54:29: 2 "OK"
Tue 2015/09/15 10:54:29: Checking line: OK
Tue 2015/09/15 10:54:29: AT reply state: 1
Tue 2015/09/15 10:54:29: RECEIVED frametype 0x00/length 0x0F/15
Tue 2015/09/15 10:54:29: 41A|54T|2B+|43C|52R|43C|3D=|311|0D |0D |0A |4FO|4BK|0D |0A      AT+CRC=1...OK.. 
Tue 2015/09/15 10:54:29: SENDING frametype 0x00/length 0x0A/10
Tue 2015/09/15 10:54:29: 41A|54T|2B+|43C|43C|57W|41A|3D=|311|0D                          AT+CCWA=1.      
Tue 2015/09/15 10:54:29: 1 "AT+CCWA=1"
Tue 2015/09/15 10:54:29: 2 "OK"
Tue 2015/09/15 10:54:29: Checking line: OK
Tue 2015/09/15 10:54:29: AT reply state: 1
Tue 2015/09/15 10:54:29: RECEIVED frametype 0x00/length 0x10/16
Tue 2015/09/15 10:54:29: 41A|54T|2B+|43C|43C|57W|41A|3D=|311|0D |0D |0A |4FO|4BK|0D |0A  AT+CCWA=1...OK..
Tue 2015/09/15 10:54:29: Leaving GSM_SetIncomingCall
Tue 2015/09/15 10:54:29: Entering GSM_SetIncomingCB
Tue 2015/09/15 10:54:29: SENDING frametype 0x00/length 0x0A/10
Tue 2015/09/15 10:54:29: 41A|54T|2B+|43C|4EN|4DM|49I|3D=|3F?|0D                          AT+CNMI=?.      
Tue 2015/09/15 10:54:29: 1 "AT+CNMI=?"
Tue 2015/09/15 10:54:29: 2 "+CNMI: (0,1,2),(0,1,2,3),(0,2),(0,2),(0,1)"
Tue 2015/09/15 10:54:29: 3 "OK"
Tue 2015/09/15 10:54:29: Checking line: OK
Tue 2015/09/15 10:54:29: AT reply state: 1
Tue 2015/09/15 10:54:29: RECEIVED frametype 0x00/length 0x3E/62
Tue 2015/09/15 10:54:29: 41A|54T|2B+|43C|4EN|4DM|49I|3D=|3F?|0D |0D |0A |2B+|43C|4EN|4DM AT+CNMI=?...+CNM
Tue 2015/09/15 10:54:29: 49I|3A:|20 |28(|300|2C,|311|2C,|322|29)|2C,|28(|300|2C,|311|2C, I: (0,1,2),(0,1,
Tue 2015/09/15 10:54:29: 322|2C,|333|29)|2C,|28(|300|2C,|322|29)|2C,|28(|300|2C,|322|29) 2,3),(0,2),(0,2)
Tue 2015/09/15 10:54:29: 2C,|28(|300|2C,|311|29)|0D |0A |0D |0A |4FO|4BK|0D |0A          ,(0,1)....OK..  
Tue 2015/09/15 10:54:29: Parsing range: (0,1,2),(0,1,2,3),(0,2),(0,2),(0,1)
Tue 2015/09/15 10:54:29: Returning range: 0, 1, 2, -1
Tue 2015/09/15 10:54:29: Parsing range: (0,1,2,3),(0,2),(0,2),(0,1)
Tue 2015/09/15 10:54:29: Returning range: 0, 1, 2, 3, -1
Tue 2015/09/15 10:54:29: Parsing range: (0,2),(0,2),(0,1)
Tue 2015/09/15 10:54:29: Returning range: 0, 2, -1
Tue 2015/09/15 10:54:29: Parsing range: (0,2),(0,1)
Tue 2015/09/15 10:54:29: Returning range: 0, 2, -1
Tue 2015/09/15 10:54:29: Enabling incoming CB
Tue 2015/09/15 10:54:29: SENDING frametype 0x00/length 0x0D/13
Tue 2015/09/15 10:54:29: 41A|54T|2B+|43C|4EN|4DM|49I|3D=|322|2C,|2C,|322|0D              AT+CNMI=2,,2.   
Tue 2015/09/15 10:54:29: 1 "AT+CNMI=2,,2"
Tue 2015/09/15 10:54:29: 2 "OK"
Tue 2015/09/15 10:54:29: Checking line: OK
Tue 2015/09/15 10:54:29: AT reply state: 1
Tue 2015/09/15 10:54:29: RECEIVED frametype 0x00/length 0x13/19
Tue 2015/09/15 10:54:29: 41A|54T|2B+|43C|4EN|4DM|49I|3D=|322|2C,|2C,|322|0D |0D |0A |4FO AT+CNMI=2,,2...O
Tue 2015/09/15 10:54:29: 4BK|0D |0A                                                      K..             
Tue 2015/09/15 10:54:29: Leaving GSM_SetIncomingCB
Tue 2015/09/15 10:54:29: Entering GSM_SetIncomingSMS
Tue 2015/09/15 10:54:29: Getting available SMS memories
Tue 2015/09/15 10:54:29: SENDING frametype 0x00/length 0x0A/10
Tue 2015/09/15 10:54:29: 41A|54T|2B+|43C|50P|4DM|53S|3D=|3F?|0D                          AT+CPMS=?.      
Tue 2015/09/15 10:54:29: 1 "AT+CPMS=?"
Tue 2015/09/15 10:54:29: 2 "+CPMS: ("ME","SM"),("ME","SM"),("ME","SM")"
Tue 2015/09/15 10:54:29: 3 "OK"
Tue 2015/09/15 10:54:29: Checking line: OK
Tue 2015/09/15 10:54:29: AT reply state: 1
Tue 2015/09/15 10:54:29: RECEIVED frametype 0x00/length 0x3E/62
Tue 2015/09/15 10:54:29: 41A|54T|2B+|43C|50P|4DM|53S|3D=|3F?|0D |0D |0A |2B+|43C|50P|4DM AT+CPMS=?...+CPM
Tue 2015/09/15 10:54:29: 53S|3A:|20 |28(|22"|4DM|45E|22"|2C,|22"|53S|4DM|22"|29)|2C,|28( S: ("ME","SM"),(
Tue 2015/09/15 10:54:29: 22"|4DM|45E|22"|2C,|22"|53S|4DM|22"|29)|2C,|28(|22"|4DM|45E|22" "ME","SM"),("ME"
Tue 2015/09/15 10:54:29: 2C,|22"|53S|4DM|22"|29)|0D |0A |0D |0A |4FO|4BK|0D |0A          ,"SM")....OK..  
Tue 2015/09/15 10:54:29: Available SMS memories received: read: ME : ok, SM : ok, save: ME : ok, SM = ok, Motorola = no
Tue 2015/09/15 10:54:29: Setting SMS memory type to ME
Tue 2015/09/15 10:54:29: SENDING frametype 0x00/length 0x0D/13
Tue 2015/09/15 10:54:29: 41A|54T|2B+|43C|50P|4DM|53S|3D=|22"|4DM|45E|22"|0D              AT+CPMS="ME".   
Tue 2015/09/15 10:54:29: 1 "AT+CPMS="ME""
Tue 2015/09/15 10:54:29: 2 "+CPMS: 0,50,0,50,4,30"
Tue 2015/09/15 10:54:29: 3 "OK"
Tue 2015/09/15 10:54:29: Checking line: OK
Tue 2015/09/15 10:54:29: AT reply state: 1
Tue 2015/09/15 10:54:29: RECEIVED frametype 0x00/length 0x2C/44
Tue 2015/09/15 10:54:29: 41A|54T|2B+|43C|50P|4DM|53S|3D=|22"|4DM|45E|22"|0D |0D |0A |2B+ AT+CPMS="ME"...+
Tue 2015/09/15 10:54:29: 43C|50P|4DM|53S|3A:|20 |300|2C,|355|300|2C,|300|2C,|355|300|2C, CPMS: 0,50,0,50,
Tue 2015/09/15 10:54:29: 344|2C,|333|300|0D |0A |0D |0A |4FO|4BK|0D |0A                  4,30....OK..    
Tue 2015/09/15 10:54:29: Enabling incoming SMS
Tue 2015/09/15 10:54:29: SENDING frametype 0x00/length 0x0E/14
Tue 2015/09/15 10:54:29: 41A|54T|2B+|43C|4EN|4DM|49I|3D=|322|2C,|2C,|2C,|322|0D          AT+CNMI=2,,,2.  
Tue 2015/09/15 10:54:29: 1 "AT+CNMI=2,,,2"
Tue 2015/09/15 10:54:29: 2 "OK"
Tue 2015/09/15 10:54:29: Checking line: OK
Tue 2015/09/15 10:54:29: AT reply state: 1
Tue 2015/09/15 10:54:29: RECEIVED frametype 0x00/length 0x14/20
Tue 2015/09/15 10:54:29: 41A|54T|2B+|43C|4EN|4DM|49I|3D=|322|2C,|2C,|2C,|322|0D |0D |0A  AT+CNMI=2,,,2...
Tue 2015/09/15 10:54:29: 4FO|4BK|0D |0A                                                  OK..            
Tue 2015/09/15 10:54:29: SENDING frametype 0x00/length 0x0C/12
Tue 2015/09/15 10:54:29: 41A|54T|2B+|43C|4EN|4DM|49I|3D=|322|2C,|311|0D                  AT+CNMI=2,1.    
Tue 2015/09/15 10:54:29: 1 "AT+CNMI=2,1"
Tue 2015/09/15 10:54:29: 2 "OK"
Tue 2015/09/15 10:54:29: Checking line: OK
Tue 2015/09/15 10:54:29: AT reply state: 1
Tue 2015/09/15 10:54:29: RECEIVED frametype 0x00/length 0x12/18
Tue 2015/09/15 10:54:29: 41A|54T|2B+|43C|4EN|4DM|49I|3D=|322|2C,|311|0D |0D |0A |4FO|4BK AT+CNMI=2,1...OK
Tue 2015/09/15 10:54:29: 0D |0A                                                          ..              
Tue 2015/09/15 10:54:29: Leaving GSM_SetIncomingSMS
Tue 2015/09/15 10:54:29: Entering GSM_SetIncomingUSSD
Tue 2015/09/15 10:54:29: Enabling incoming USSD
Tue 2015/09/15 10:54:29: SENDING frametype 0x00/length 0x0A/10
Tue 2015/09/15 10:54:29: 41A|54T|2B+|43C|55U|53S|44D|3D=|311|0D                          AT+CUSD=1.      
Tue 2015/09/15 10:54:29: 1 "AT+CUSD=1"
Tue 2015/09/15 10:54:29: 2 "OK"
Tue 2015/09/15 10:54:29: Checking line: OK
Tue 2015/09/15 10:54:29: AT reply state: 1
Tue 2015/09/15 10:54:29: RECEIVED frametype 0x00/length 0x10/16
Tue 2015/09/15 10:54:29: 41A|54T|2B+|43C|55U|53S|44D|3D=|311|0D |0D |0A |4FO|4BK|0D |0A  AT+CUSD=1...OK..
Tue 2015/09/15 10:54:29: Leaving GSM_SetIncomingUSSD
Tue 2015/09/15 10:54:29: Entering GSM_GetSignalQuality
Tue 2015/09/15 10:54:29: Getting signal quality info
Tue 2015/09/15 10:54:29: SENDING frametype 0x00/length 0x07/7
Tue 2015/09/15 10:54:29: 41A|54T|2B+|43C|53S|51Q|0D                                      AT+CSQ.         
Tue 2015/09/15 10:54:29: 1 "AT+CSQ"
Tue 2015/09/15 10:54:29: 2 "+CSQ: 24,99"
Tue 2015/09/15 10:54:29: 3 "OK"
Tue 2015/09/15 10:54:29: Checking line: OK
Tue 2015/09/15 10:54:29: AT reply state: 1
Tue 2015/09/15 10:54:29: RECEIVED frametype 0x00/length 0x1C/28
Tue 2015/09/15 10:54:29: 41A|54T|2B+|43C|53S|51Q|0D |0D |0A |2B+|43C|53S|51Q|3A:|20 |322 AT+CSQ...+CSQ: 2
Tue 2015/09/15 10:54:29: 344|2C,|399|399|0D |0A |0D |0A |4FO|4BK|0D |0A                  4,99....OK..    
Tue 2015/09/15 10:54:29: Signal quality info received
Tue 2015/09/15 10:54:29: Parsing +CSQ: 24,99 with +CSQ: @i, @i
Tue 2015/09/15 10:54:29: Parsed int 24
Tue 2015/09/15 10:54:29: Parsed int 99
Tue 2015/09/15 10:54:29: Leaving GSM_GetSignalQuality
Tue 2015/09/15 10:54:34: Entering GSM_GetSignalQuality
Tue 2015/09/15 10:54:34: Getting signal quality info
Tue 2015/09/15 10:54:34: SENDING frametype 0x00/length 0x07/7
Tue 2015/09/15 10:54:34: 41A|54T|2B+|43C|53S|51Q|0D                                      AT+CSQ.         
Tue 2015/09/15 10:54:34: 1 "^BOOT:44964621,0,0,0,99"
Tue 2015/09/15 10:54:34: Checking line: ^BOOT:44964621,0,0,0,99
Tue 2015/09/15 10:54:34: AT reply state: 4
Tue 2015/09/15 10:54:34: RECEIVED frametype 0x00/length 0x19/25
Tue 2015/09/15 10:54:34: 5E^|42B|4FO|4FO|54T|3A:|344|344|399|366|344|366|322|311|2C,|300 ^BOOT:44964621,0
Tue 2015/09/15 10:54:34: 2C,|300|2C,|300|2C,|399|399|0D |0A                              ,0,0,99..       
Tue 2015/09/15 10:54:34: 1 "^RSSI:23"
Tue 2015/09/15 10:54:34: Checking line: ^RSSI:23
Tue 2015/09/15 10:54:34: AT reply state: 4
Tue 2015/09/15 10:54:34: RECEIVED frametype 0x00/length 0x0A/10
Tue 2015/09/15 10:54:34: 5E^|52R|53S|53S|49I|3A:|322|333|0D |0A                          ^RSSI:23..      
Tue 2015/09/15 10:54:34: 1 "^CSNR:-67,-2"
Tue 2015/09/15 10:54:34: Checking line: ^CSNR:-67,-2
Tue 2015/09/15 10:54:34: AT reply state: 4
Tue 2015/09/15 10:54:34: RECEIVED frametype 0x00/length 0x0E/14
Tue 2015/09/15 10:54:34: 5E^|43C|53S|4EN|52R|3A:|2D-|366|377|2C,|2D-|322|0D |0A          ^CSNR:-67,-2..  
Tue 2015/09/15 10:54:34: 1 "AT+CSQ"
Tue 2015/09/15 10:54:34: 2 "+CSQ: 24,99"
Tue 2015/09/15 10:54:34: 3 "OK"
Tue 2015/09/15 10:54:34: Checking line: OK
Tue 2015/09/15 10:54:34: AT reply state: 1
Tue 2015/09/15 10:54:34: RECEIVED frametype 0x00/length 0x1C/28
Tue 2015/09/15 10:54:34: 41A|54T|2B+|43C|53S|51Q|0D |0D |0A |2B+|43C|53S|51Q|3A:|20 |322 AT+CSQ...+CSQ: 2
Tue 2015/09/15 10:54:34: 344|2C,|399|399|0D |0A |0D |0A |4FO|4BK|0D |0A                  4,99....OK..    
Tue 2015/09/15 10:54:34: Signal quality info received
Tue 2015/09/15 10:54:34: Parsing +CSQ: 24,99 with +CSQ: @i, @i
Tue 2015/09/15 10:54:34: Parsed int 24
Tue 2015/09/15 10:54:34: Parsed int 99
Tue 2015/09/15 10:54:34: Leaving GSM_GetSignalQuality
Tue 2015/09/15 10:54:39: Entering GSM_GetSignalQuality
Tue 2015/09/15 10:54:39: Getting signal quality info
Tue 2015/09/15 10:54:39: SENDING frametype 0x00/length 0x07/7
Tue 2015/09/15 10:54:39: 41A|54T|2B+|43C|53S|51Q|0D                                      AT+CSQ.         
Tue 2015/09/15 10:54:39: 1 "^RSSI:23"
Tue 2015/09/15 10:54:39: Checking line: ^RSSI:23
Tue 2015/09/15 10:54:39: AT reply state: 4
Tue 2015/09/15 10:54:39: RECEIVED frametype 0x00/length 0x0A/10
Tue 2015/09/15 10:54:39: 5E^|52R|53S|53S|49I|3A:|322|333|0D |0A                          ^RSSI:23..      
Tue 2015/09/15 10:54:39: 1 "^CSNR:-69,-5"
Tue 2015/09/15 10:54:39: Checking line: ^CSNR:-69,-5
Tue 2015/09/15 10:54:39: AT reply state: 4
Tue 2015/09/15 10:54:39: RECEIVED frametype 0x00/length 0x0E/14
Tue 2015/09/15 10:54:39: 5E^|43C|53S|4EN|52R|3A:|2D-|366|399|2C,|2D-|355|0D |0A          ^CSNR:-69,-5..  
Tue 2015/09/15 10:54:39: 1 "AT+CSQ"
Tue 2015/09/15 10:54:39: 2 "+CSQ: 24,99"
Tue 2015/09/15 10:54:39: 3 "OK"
Tue 2015/09/15 10:54:39: Checking line: OK
Tue 2015/09/15 10:54:39: AT reply state: 1
Tue 2015/09/15 10:54:39: RECEIVED frametype 0x00/length 0x1C/28
Tue 2015/09/15 10:54:39: 41A|54T|2B+|43C|53S|51Q|0D |0D |0A |2B+|43C|53S|51Q|3A:|20 |322 AT+CSQ...+CSQ: 2
Tue 2015/09/15 10:54:39: 344|2C,|399|399|0D |0A |0D |0A |4FO|4BK|0D |0A                  4,99....OK..    
Tue 2015/09/15 10:54:39: Signal quality info received
Tue 2015/09/15 10:54:39: Parsing +CSQ: 24,99 with +CSQ: @i, @i
Tue 2015/09/15 10:54:39: Parsed int 24
Tue 2015/09/15 10:54:39: Parsed int 99
Tue 2015/09/15 10:54:39: Leaving GSM_GetSignalQuality
Tue 2015/09/15 10:54:44: Entering GSM_GetSignalQuality
Tue 2015/09/15 10:54:44: Getting signal quality info
Tue 2015/09/15 10:54:44: SENDING frametype 0x00/length 0x07/7
Tue 2015/09/15 10:54:44: 41A|54T|2B+|43C|53S|51Q|0D                                      AT+CSQ.         
Tue 2015/09/15 10:54:44: 1 "AT+CSQ"
Tue 2015/09/15 10:54:44: 2 "+CSQ: 24,99"
Tue 2015/09/15 10:54:44: 3 "OK"
Tue 2015/09/15 10:54:44: Checking line: OK
Tue 2015/09/15 10:54:44: AT reply state: 1
Tue 2015/09/15 10:54:44: RECEIVED frametype 0x00/length 0x1C/28
Tue 2015/09/15 10:54:44: 41A|54T|2B+|43C|53S|51Q|0D |0D |0A |2B+|43C|53S|51Q|3A:|20 |322 AT+CSQ...+CSQ: 2
Tue 2015/09/15 10:54:44: 344|2C,|399|399|0D |0A |0D |0A |4FO|4BK|0D |0A                  4,99....OK..    
Tue 2015/09/15 10:54:44: Signal quality info received
Tue 2015/09/15 10:54:44: Parsing +CSQ: 24,99 with +CSQ: @i, @i
Tue 2015/09/15 10:54:44: Parsed int 24
Tue 2015/09/15 10:54:44: Parsed int 99
Tue 2015/09/15 10:54:44: Leaving GSM_GetSignalQuality
Tue 2015/09/15 10:54:49: Entering GSM_GetSignalQuality
Tue 2015/09/15 10:54:49: Getting signal quality info
Tue 2015/09/15 10:54:49: SENDING frametype 0x00/length 0x07/7
Tue 2015/09/15 10:54:49: 41A|54T|2B+|43C|53S|51Q|0D                                      AT+CSQ.         
Tue 2015/09/15 10:54:49: 1 "AT+CSQ"
Tue 2015/09/15 10:54:49: 2 "+CSQ: 24,99"
Tue 2015/09/15 10:54:49: 3 "OK"
Tue 2015/09/15 10:54:49: Checking line: OK
Tue 2015/09/15 10:54:49: AT reply state: 1
Tue 2015/09/15 10:54:49: RECEIVED frametype 0x00/length 0x1C/28
Tue 2015/09/15 10:54:49: 41A|54T|2B+|43C|53S|51Q|0D |0D |0A |2B+|43C|53S|51Q|3A:|20 |322 AT+CSQ...+CSQ: 2
Tue 2015/09/15 10:54:49: 344|2C,|399|399|0D |0A |0D |0A |4FO|4BK|0D |0A                  4,99....OK..    
Tue 2015/09/15 10:54:49: Signal quality info received
Tue 2015/09/15 10:54:49: Parsing +CSQ: 24,99 with +CSQ: @i, @i
Tue 2015/09/15 10:54:49: Parsed int 24
Tue 2015/09/15 10:54:49: Parsed int 99
Tue 2015/09/15 10:54:49: Leaving GSM_GetSignalQuality
Tue 2015/09/15 10:54:54: Entering GSM_GetSignalQuality
Tue 2015/09/15 10:54:54: Getting signal quality info
Tue 2015/09/15 10:54:54: SENDING frametype 0x00/length 0x07/7
Tue 2015/09/15 10:54:54: 41A|54T|2B+|43C|53S|51Q|0D                                      AT+CSQ.         
Tue 2015/09/15 10:54:54: 1 "AT+CSQ"
Tue 2015/09/15 10:54:54: 2 "+CSQ: 24,99"
Tue 2015/09/15 10:54:54: 3 "OK"
Tue 2015/09/15 10:54:54: Checking line: OK
Tue 2015/09/15 10:54:54: AT reply state: 1
Tue 2015/09/15 10:54:54: RECEIVED frametype 0x00/length 0x1C/28
Tue 2015/09/15 10:54:54: 41A|54T|2B+|43C|53S|51Q|0D |0D |0A |2B+|43C|53S|51Q|3A:|20 |322 AT+CSQ...+CSQ: 2
Tue 2015/09/15 10:54:54: 344|2C,|399|399|0D |0A |0D |0A |4FO|4BK|0D |0A                  4,99....OK..    
Tue 2015/09/15 10:54:54: Signal quality info received
Tue 2015/09/15 10:54:54: Parsing +CSQ: 24,99 with +CSQ: @i, @i
Tue 2015/09/15 10:54:54: Parsed int 24
Tue 2015/09/15 10:54:54: Parsed int 99
Tue 2015/09/15 10:54:54: Leaving GSM_GetSignalQuality
Tue 2015/09/15 10:54:55: Entering GSM_SetIncomingSMS
Tue 2015/09/15 10:54:55: Disabling incoming SMS
Tue 2015/09/15 10:54:55: SENDING frametype 0x00/length 0x0E/14
Tue 2015/09/15 10:54:55: 41A|54T|2B+|43C|4EN|4DM|49I|3D=|322|2C,|2C,|2C,|300|0D          AT+CNMI=2,,,0.  
Tue 2015/09/15 10:54:55: 1 "AT+CNMI=2,,,0"
Tue 2015/09/15 10:54:55: 2 "OK"
Tue 2015/09/15 10:54:55: Checking line: OK
Tue 2015/09/15 10:54:55: AT reply state: 1
Tue 2015/09/15 10:54:55: RECEIVED frametype 0x00/length 0x14/20
Tue 2015/09/15 10:54:55: 41A|54T|2B+|43C|4EN|4DM|49I|3D=|322|2C,|2C,|2C,|300|0D |0D |0A  AT+CNMI=2,,,0...
Tue 2015/09/15 10:54:55: 4FO|4BK|0D |0A                                                  OK..            
Tue 2015/09/15 10:54:55: SENDING frametype 0x00/length 0x0C/12
Tue 2015/09/15 10:54:55: 41A|54T|2B+|43C|4EN|4DM|49I|3D=|322|2C,|300|0D                  AT+CNMI=2,0.    
Tue 2015/09/15 10:54:55: 1 "AT+CNMI=2,0"
Tue 2015/09/15 10:54:55: 2 "OK"
Tue 2015/09/15 10:54:55: Checking line: OK
Tue 2015/09/15 10:54:55: AT reply state: 1
Tue 2015/09/15 10:54:55: RECEIVED frametype 0x00/length 0x12/18
Tue 2015/09/15 10:54:55: 41A|54T|2B+|43C|4EN|4DM|49I|3D=|322|2C,|300|0D |0D |0A |4FO|4BK AT+CNMI=2,0...OK
Tue 2015/09/15 10:54:55: 0D |0A                                                          ..              
Tue 2015/09/15 10:54:55: Leaving GSM_SetIncomingSMS
Tue 2015/09/15 10:54:55: Entering GSM_SetIncomingCall
Tue 2015/09/15 10:54:55: SENDING frametype 0x00/length 0x0A/10
Tue 2015/09/15 10:54:55: 41A|54T|2B+|43C|43C|57W|41A|3D=|300|0D                          AT+CCWA=0.      
Tue 2015/09/15 10:54:55: 1 "AT+CCWA=0"
Tue 2015/09/15 10:54:55: 2 "OK"
Tue 2015/09/15 10:54:55: Checking line: OK
Tue 2015/09/15 10:54:55: AT reply state: 1
Tue 2015/09/15 10:54:55: RECEIVED frametype 0x00/length 0x10/16
Tue 2015/09/15 10:54:55: 41A|54T|2B+|43C|43C|57W|41A|3D=|300|0D |0D |0A |4FO|4BK|0D |0A  AT+CCWA=0...OK..
Tue 2015/09/15 10:54:55: Disabling incoming call notification
Tue 2015/09/15 10:54:55: Leaving GSM_SetIncomingCall
Tue 2015/09/15 10:54:55: Entering GSM_SetIncomingCB
Tue 2015/09/15 10:54:55: Disabling incoming CB
Tue 2015/09/15 10:54:55: SENDING frametype 0x00/length 0x0D/13
Tue 2015/09/15 10:54:55: 41A|54T|2B+|43C|4EN|4DM|49I|3D=|322|2C,|2C,|300|0D              AT+CNMI=2,,0.   
Tue 2015/09/15 10:54:55: 1 "AT+CNMI=2,,0"
Tue 2015/09/15 10:54:55: 2 "OK"
Tue 2015/09/15 10:54:55: Checking line: OK
Tue 2015/09/15 10:54:55: AT reply state: 1
Tue 2015/09/15 10:54:55: RECEIVED frametype 0x00/length 0x13/19
Tue 2015/09/15 10:54:55: 41A|54T|2B+|43C|4EN|4DM|49I|3D=|322|2C,|2C,|300|0D |0D |0A |4FO AT+CNMI=2,,0...O
Tue 2015/09/15 10:54:55: 4BK|0D |0A                                                      K..             
Tue 2015/09/15 10:54:55: Leaving GSM_SetIncomingCB
Tue 2015/09/15 10:54:55: Entering GSM_SetIncomingUSSD
Tue 2015/09/15 10:54:55: Terminating possible incoming USSD
Tue 2015/09/15 10:54:55: SENDING frametype 0x00/length 0x0A/10
Tue 2015/09/15 10:54:55: 41A|54T|2B+|43C|55U|53S|44D|3D=|322|0D                          AT+CUSD=2.      
Tue 2015/09/15 10:54:55: 1 "AT+CUSD=2"
Tue 2015/09/15 10:54:55: 2 "ERROR"
Tue 2015/09/15 10:54:55: Checking line: ERROR
Tue 2015/09/15 10:54:55: AT reply state: 3
Tue 2015/09/15 10:54:55: RECEIVED frametype 0x00/length 0x13/19
Tue 2015/09/15 10:54:55: 41A|54T|2B+|43C|55U|53S|44D|3D=|322|0D |0D |0A |45E|52R|52R|4FO AT+CUSD=2...ERRO
Tue 2015/09/15 10:54:55: 52R|0D |0A                                                      R..             
Tue 2015/09/15 10:54:55: Disabling incoming USSD
Tue 2015/09/15 10:54:55: SENDING frametype 0x00/length 0x0A/10
Tue 2015/09/15 10:54:55: 41A|54T|2B+|43C|55U|53S|44D|3D=|300|0D                          AT+CUSD=0.      
Tue 2015/09/15 10:54:55: 1 "AT+CUSD=0"
Tue 2015/09/15 10:54:55: 2 "OK"
Tue 2015/09/15 10:54:55: Checking line: OK
Tue 2015/09/15 10:54:55: AT reply state: 1
Tue 2015/09/15 10:54:55: RECEIVED frametype 0x00/length 0x10/16
Tue 2015/09/15 10:54:55: 41A|54T|2B+|43C|55U|53S|44D|3D=|300|0D |0D |0A |4FO|4BK|0D |0A  AT+CUSD=0...OK..
Tue 2015/09/15 10:54:55: Leaving GSM_SetIncomingUSSD
Tue 2015/09/15 10:54:55: [Terminating]
Tue 2015/09/15 10:54:55: [Closing]

It seems also that it depends partially on the connection speed (if I set at115200 it takes 2 minutes, if I left it with at and it sets 19200 by default it takes 2x time). Now I'll try with changes of the other branch. :) Thank you very much!

**Comment by Bowser** [comment]
This is the log of a test with the branch version.
We're not coming out: it took even longer now (7 minutes), but probably it's depends on chance and not on the changes.

http://pastebin.com/fbgF6irW

**Comment by Bowser** [comment]
I noted your last commit to master and I changed the speed param in gammurc for a test.
I noted that increasing the speed (using again the delay-rewrite branch version) from 19200 to 115200 the lag between the beginning and the start of the communication with the modem decreases of a good half (2 minutes). Could this way be good to find a solution?

**Comment by nijel** [comment]
That's not really a solution, but sticking with slow speed doesn't make
sense these days when anything is anyway USB based.

-- 
	Michal Čihař | http://cihar.com | http://blog.cihar.com

**Comment by nijel** [comment]
Can you please try it now (preferably with both ``master`` and ``delay-rewrite`` branches)?

**Comment by Bowser** [comment]
I think that the last changes in master have solved the problem (despite a timeout the first time i run gammu):
Tue 2015/09/15 12:38:44: [Gammu            - 1.36.6]
Tue 2015/09/15 12:38:44: [Connection       - "at115200"]
Tue 2015/09/15 12:38:44: [Connection index - 0]
Tue 2015/09/15 12:38:44: [Model type       - "at"]
Tue 2015/09/15 12:38:44: [Device           - "/dev/ttyUSB2"]
Tue 2015/09/15 12:38:44: [Running on       - Linux, kernel 3.16.0-4-amd64 (#1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04))]
Tue 2015/09/15 12:38:44: [Module           - "A2D|iPAQ|at|M20|S25|MC35|TC35|C35i|S65|S300|5110|5130|5190|5210|6110|6130|6150|6190|6210|6250|6310|6310i|6510|7110|8210|$
Tue 2015/09/15 12:38:44: Serial device: DTR is up, RTS is up, CAR is down, CTS is down
Tue 2015/09/15 12:38:44: Setting speed to 115200
Tue 2015/09/15 12:38:44: Escaping SMS mode
Tue 2015/09/15 12:38:44: SENDING frame type 0x00/length 0x02/2
Tue 2015/09/15 12:38:44: 1B |0D                                                          ..
Tue 2015/09/15 12:38:45: Sending simple AT command to wake up some devices
Tue 2015/09/15 12:38:45: SENDING frame type 0x00/length 0x03/3
Tue 2015/09/15 12:38:45: 41A|54T|0D                                                      AT.
Tue 2015/09/15 12:38:46: 1 "AT"
Tue 2015/09/15 12:38:46: 2 "OK"
Tue 2015/09/15 12:38:46: Checking line: OK
Tue 2015/09/15 12:38:46: AT reply state: 1
Tue 2015/09/15 12:38:46: RECEIVED frame type 0x00/length 0x09/9
Tue 2015/09/15 12:38:46: 41A|54T|0D |0D |0A |4FO|4BK|0D |0A                              AT...OK..
Tue 2015/09/15 12:38:46: Enabling echo
Tue 2015/09/15 12:38:46: SENDING frame type 0x00/length 0x05/5
Tue 2015/09/15 12:38:46: 41A|54T|45E|311|0D                                              ATE1.
Tue 2015/09/15 12:38:46: 1 "ATE1"
Tue 2015/09/15 12:38:46: 2 "OK"
Tue 2015/09/15 12:38:46: Checking line: OK
Tue 2015/09/15 12:38:46: AT reply state: 1
Tue 2015/09/15 12:38:46: RECEIVED frame type 0x00/length 0x0B/11
Tue 2015/09/15 12:38:46: 41A|54T|45E|311|0D |0D |0A |4FO|4BK|0D |0A                      ATE1...OK..

However now I'll try even with delay-rewrite version. :+1:

**Comment by Bowser** [comment]
delay-rewrite instead doesn't work.

root@system:~/Lavoro/gammu-examples# python gammu_test.py
Traceback (most recent call last):
  File "gammu_test.py", line 89, in <module>
    main()
  File "gammu_test.py", line 59, in main
    state_machine.Init()
gammu.ERR_TIMEOUT: {'Text': u'Nessuna risposta nel tempo specificato. Probabilmente il telefono non \xe8 connesso.', 'Code': 14, 'Where': 'Init'}
root@system:~/Lavoro/gammu-examples# python gammu_test.py
Traceback (most recent call last):
  File "gammu_test.py", line 89, in <module>
    main()
  File "gammu_test.py", line 59, in main
    state_machine.Init()
gammu.ERR_TIMEOUT: {'Text': u'Nessuna risposta nel tempo specificato. Probabilmente il telefono non \xe8 connesso.', 'Code': 14, 'Where': 'Init'}
^C
root@system:~/Lavoro/gammu-examples# python gammu_test.py
Traceback (most recent call last):
  File "gammu_test.py", line 89, in <module>
    main()
  File "gammu_test.py", line 59, in main
    state_machine.Init()
gammu.system: {'Text': u'Nessuna risposta nel tempo specificato. Probabilmente il telefono non \xe8 connesso.', 'Code': 14, 'Where': 'Init'}
^C
root@damiano-test:~/Lavoro/gammu-examples# python gammu_test.py
^C
root@damiano-test:~/Lavoro/gammu-examples# python gammu_test.py
^C

In the last two tests (without changing anything) it sent the command ATE1 at the beginning and then didn't do anything else, it just was receiving CSNR, RSSI and BOOT signals.

**Comment by nijel** [comment]
Okay, let's forget that and avoid touching working code :-). Anyway your issue is now fixed in master, thanks for testing that.

**Comment by Bowser** [comment]
These days I'm improving the performances of my application (which uses gammu for all GSM communications), and I'm still experiencing some slow initializations.
They happen irregularly, especially when I have to restart the app (so the modem used to work until some moments before), having the same behaviour of the last time.

It blocks without sending the ATE command for some minutes, receiving without doing anything these commands from the modem.

Mon 2015/10/12 11:21:48: 1 "^CSNR:-63,-2"
Mon 2015/10/12 11:21:48: Checking line: ^CSNR:-63,-2
Mon 2015/10/12 11:21:48: AT reply state: 4
Mon 2015/10/12 11:21:51: 1 "^RSSI:23"
Mon 2015/10/12 11:21:51: Checking line: ^RSSI:23
Mon 2015/10/12 11:21:51: AT reply state: 4
Mon 2015/10/12 11:21:51: 1 "^CSNR:-68,-4"
Mon 2015/10/12 11:21:51: Checking line: ^CSNR:-68,-4
Mon 2015/10/12 11:21:51: AT reply state: 4
Mon 2015/10/12 11:21:53: 1 "^BOOT:44964621,0,0,0,99"
Mon 2015/10/12 11:21:53: Checking line: ^BOOT:44964621,0,0,0,99
Mon 2015/10/12 11:21:53: AT reply state: 4

Do you think that something could be done for having gammu to ignore (at all) these useless commands (as I understand it) and start the active communication with the modem without waiting some time?
Thank you again :+1:

**Comment by nijel** [comment]
It should work like that with current git, if not, then it's bug :-).

**Comment by Bowser** [comment]
One thing I didn't say until now is that I'm using, at the moment, the same modem for Gammu (via python-gammu) and Gammu-SMSD on different ports.
The first one is on /dev/ttyUSB2 (which seems to support Call Notifications) and the second on /dev/ttyUSB0.

Normally they appear to work transparently each from the other, without signaling any problem (at the contrary it helps me not to let the modem to go in sleep mode, when no sms are received).
Some times, due to changes at the code, I have to restart the Gammu-based application, especially (but not only) in that case I'm having some troubles to make it work quickly (as I said on my previous post).
Another case is when Gammu (again) seems to sleep without showing signs of life (and I have to SIGKILL the process).

I'm not sure if the double-channel communication could give some problems of incompatibility or conflict (and I don't even know if this is a predicted use-case of gammu), however usually it works good.

**Comment by nijel** [comment]
The two channels are supposed to work independently, but I doubt they are fully independent on the device side, so some problems might be caused by this...
